name: 01. CI\CD Development workflow

on:
  push:
    branches: [dev]

jobs:
  test:
    name: Testing dummy homepage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Path
        run: pwd

  deploy:
    name: Deploy to development server
    needs: [test]
    environment: development
    runs-on: dev-kolosov
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        
      - name: Build mainpage container
        run: docker compose build

      - name: Down mainpage container
        run: docker compose down
        
      - name: Up mainpage container
        run: docker compose up -d

