name: 02. CI\CD Production workflow

on:
  push:
    branches: [main]

jobs:
  test:
    name: Testing dummy homepage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Path
        run: pwd

  deploy:
    name: Deploy to production server
    environment: production
    runs-on: prod-runner
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Down auth container
        run: docker compose build

      - name: Up auth container
        run: docker compose up -d

