name: 02. CI\CD Production workflow

on:
  push:
    branches: [main]

jobs:
  test:
    name: 001. Testing dummy homepage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Path
        run: pwd

  deploy:
    name: 002. Deploy to production server
    needs: [test]
    environment: production
    runs-on: prod-runner
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Build mainpage container
        run: docker compose build

      - name: Down mainpage container
        run: docker compose down
        
      - name: Up mainpage container
        run: docker compose up -d

